from __future__ import annotations

from dataclasses import dataclass


ORDER_STATUS_PENDING = "PENDING"
ORDER_STATUS_CONFIRMED = "CONFIRMED"
ORDER_STATUS_DELIVERING = "DELIVERING"
ORDER_STATUS_PARTIALLY_DELIVERED = "PARTIALLY_DELIVERED"
ORDER_STATUS_DELIVERED = "DELIVERED"
ORDER_STATUS_CANCELLED = "CANCELLED"
ORDER_STATUS_FAILED = "FAILED"

DELIVERY_STATUS_ASSIGNED = "ASSIGNED"
DELIVERY_STATUS_PICKED_UP = "PICKED_UP"
DELIVERY_STATUS_ON_THE_WAY = "ON_THE_WAY"
DELIVERY_STATUS_PARTIALLY_DELIVERED = "PARTIALLY_DELIVERED"
DELIVERY_STATUS_DELIVERED = "DELIVERED"
DELIVERY_STATUS_FAILED = "FAILED"
DELIVERY_STATUS_CANCELLED = "CANCELLED"

ORDER_STATUSES = {
    ORDER_STATUS_PENDING,
    ORDER_STATUS_CONFIRMED,
    ORDER_STATUS_DELIVERING,
    ORDER_STATUS_PARTIALLY_DELIVERED,
    ORDER_STATUS_DELIVERED,
    ORDER_STATUS_CANCELLED,
    ORDER_STATUS_FAILED,
}

DELIVERY_STATUSES = {
    DELIVERY_STATUS_ASSIGNED,
    DELIVERY_STATUS_PICKED_UP,
    DELIVERY_STATUS_ON_THE_WAY,
    DELIVERY_STATUS_PARTIALLY_DELIVERED,
    DELIVERY_STATUS_DELIVERED,
    DELIVERY_STATUS_FAILED,
    DELIVERY_STATUS_CANCELLED,
}

ORDER_TRANSITIONS: dict[str, set[str]] = {
    ORDER_STATUS_PENDING: {ORDER_STATUS_CONFIRMED, ORDER_STATUS_CANCELLED},
    ORDER_STATUS_CONFIRMED: {ORDER_STATUS_DELIVERING, ORDER_STATUS_CANCELLED},
    ORDER_STATUS_DELIVERING: {ORDER_STATUS_PARTIALLY_DELIVERED, ORDER_STATUS_DELIVERED, ORDER_STATUS_FAILED},
    ORDER_STATUS_PARTIALLY_DELIVERED: {ORDER_STATUS_DELIVERED, ORDER_STATUS_FAILED},
    ORDER_STATUS_DELIVERED: set(),
    ORDER_STATUS_CANCELLED: set(),
    ORDER_STATUS_FAILED: set(),
}

DELIVERY_TRANSITIONS: dict[str, set[str]] = {
    DELIVERY_STATUS_ASSIGNED: {DELIVERY_STATUS_PICKED_UP, DELIVERY_STATUS_CANCELLED},
    DELIVERY_STATUS_PICKED_UP: {DELIVERY_STATUS_ON_THE_WAY, DELIVERY_STATUS_FAILED},
    DELIVERY_STATUS_ON_THE_WAY: {
        DELIVERY_STATUS_PARTIALLY_DELIVERED,
        DELIVERY_STATUS_DELIVERED,
        DELIVERY_STATUS_FAILED,
    },
    DELIVERY_STATUS_PARTIALLY_DELIVERED: {DELIVERY_STATUS_DELIVERED, DELIVERY_STATUS_FAILED},
    DELIVERY_STATUS_DELIVERED: set(),
    DELIVERY_STATUS_FAILED: set(),
    DELIVERY_STATUS_CANCELLED: set(),
}


@dataclass(frozen=True)
class TransitionError:
    code: str
    message: str


def can_transition_order(current_status: str, next_status: str) -> bool:
    current = (current_status or "").upper()
    target = (next_status or "").upper()
    if current not in ORDER_STATUSES or target not in ORDER_STATUSES:
        return False
    if current == target:
        return True
    return target in ORDER_TRANSITIONS.get(current, set())


def can_transition_delivery(current_status: str, next_status: str) -> bool:
    current = (current_status or "").upper()
    target = (next_status or "").upper()
    if current not in DELIVERY_STATUSES or target not in DELIVERY_STATUSES:
        return False
    if current == target:
        return True
    return target in DELIVERY_TRANSITIONS.get(current, set())

