export const ONBOARDING_ENGINE_VERSION = "1.0.0";
export const ONBOARDING_STORAGE_SCHEMA_VERSION = 1;
export const ONBOARDING_GUIDE_CONTENT_VERSION = "1.0.0";

export const ONBOARDING_STORAGE_NAMESPACE = `usc.onboarding.v${ONBOARDING_STORAGE_SCHEMA_VERSION}`;

