import type { OnboardingStep } from "./types";

export const ONBOARDING_STEPS: OnboardingStep[] = [
  {
    id: "welcome",
    eyebrow: "Старт",
    title: "Добро пожаловать в USC",
    description: "Пройдемся по основным действиям: витрина, корзина, аналитика, AI и профиль. Гайд короткий, но практичный.",
    mode: "info",
    screen: "home",
    accent: "brand",
  },
  {
    id: "open_drawer",
    eyebrow: "Навигация",
    title: "Откройте меню",
    description: "Через drawer доступны разделы, переключение роли, уведомления и служебные экраны. Начнем с него.",
    mode: "interaction_required",
    screen: "home",
    targetSelector: '[data-tour-id="top-burger"]',
    actionHint: "Нажмите на кнопку меню, чтобы продолжить.",
    accent: "action",
  },
  {
    id: "home_search",
    eyebrow: "Витрина",
    title: "Поиск работает прямо на главной",
    description: "Здесь можно быстро искать товары и поставщиков без перехода в отдельный экран. Это самый быстрый вход в закупку.",
    mode: "info",
    screen: "home",
    targetSelector: '[data-tour-id="home-search-box"]',
    accent: "brand",
  },
  {
    id: "home_category",
    eyebrow: "Витрина",
    title: "Смените категорию",
    description: "Прокрутите карусель и выберите другую категорию. Так вы увидите, как быстро меняется ассортимент на витрине.",
    mode: "interaction_required",
    screen: "home",
    targetSelector: '[data-tour-id="home-categories"]',
    actionHint: "Выберите любую другую категорию, чтобы продолжить.",
    accent: "action",
  },
  {
    id: "home_products",
    eyebrow: "Витрина",
    title: "Карточки товара уже готовы к действию",
    description: "На карточке сразу видны цена, поставщик и ключевые свойства. Из этого экрана пользователь обычно идет прямо в корзину.",
    mode: "info",
    screen: "home",
    targetSelector: '[data-tour-id="home-product-grid"]',
    accent: "insight",
  },
  {
    id: "tab_cart",
    eyebrow: "Поток заказа",
    title: "Перейдите в корзину",
    description: "Теперь пройдем реальный маршрут пользователя: из витрины в оформление заказа.",
    mode: "interaction_required",
    targetSelector: '[data-tour-id="tab-cart"]',
    actionHint: "Нажмите на вкладку корзины внизу экрана.",
    accent: "action",
  },
  {
    id: "cart_checkout",
    eyebrow: "Поток заказа",
    title: "Откройте оформление заказа",
    description: "В checkout собираются адрес, карта, комментарий и тип доставки. Это главный экран для завершения закупки.",
    mode: "interaction_required",
    screen: "cart",
    targetSelector: '[data-tour-id="cart-open-checkout"]',
    actionHint: "Откройте оформление заказа, чтобы продолжить.",
    accent: "action",
  },
  {
    id: "checkout_map",
    eyebrow: "Поток заказа",
    title: "Карта и детали доставки",
    description: "Внутри checkout можно выбрать точку на карте, добавить координаты и комментарий для курьера. Это снижает риск ошибки на последней миле.",
    mode: "info",
    screen: "cart",
    targetSelector: '[data-tour-id="cart-checkout-panel"]',
    accent: "insight",
  },
  {
    id: "tab_analytics",
    eyebrow: "Контроль",
    title: "Откройте аналитику",
    description: "После заказа логично перейти к метрикам: выручка, отмены, сезонность и точки роста.",
    mode: "interaction_required",
    targetSelector: '[data-tour-id="tab-analytics"]',
    actionHint: "Нажмите на вкладку аналитики.",
    accent: "action",
  },
  {
    id: "analytics_overview",
    eyebrow: "Контроль",
    title: "Ключевая аналитика",
    description: "Этот блок дает быстрый снимок бизнеса: revenue, delivery, cancel rate и динамику. Он должен читаться за несколько секунд.",
    mode: "info",
    screen: "analytics",
    targetSelector: '[data-tour-id="analytics-kpi-overview"]',
    accent: "insight",
  },
  {
    id: "tab_ai",
    eyebrow: "Решения",
    title: "Перейдите в AI",
    description: "Следующий слой после метрик: задать вопрос по данным и получить объяснение, а не только цифры.",
    mode: "interaction_required",
    targetSelector: '[data-tour-id="tab-ai"]',
    actionHint: "Нажмите на вкладку AI.",
    accent: "action",
  },
  {
    id: "ai_assistant",
    eyebrow: "Решения",
    title: "AI-ассистент и сценарии",
    description: "Здесь можно задавать вопросы по данным компании, а ниже запускать what-if сценарии для экспериментов перед реальным действием.",
    mode: "interaction_required",
    screen: "ai",
    targetSelector: '[data-tour-id="ai-input-row"]',
    actionHint: "Отправьте вопрос в AI и дождитесь ответа, чтобы продолжить.",
    accent: "success",
  },
  {
    id: "tab_profile",
    eyebrow: "Контекст",
    title: "Откройте профиль",
    description: "Финальный шаг маршрута: проверка своей роли, компании и рабочего контекста.",
    mode: "interaction_required",
    targetSelector: '[data-tour-id="tab-profile"]',
    actionHint: "Нажмите на вкладку профиля.",
    accent: "action",
  },
  {
    id: "profile_company",
    eyebrow: "Контекст",
    title: "Профиль и активная компания",
    description: "В этом экране видно, от имени какой компании работает пользователь. Это особенно важно для заказов, аналитики и ролей buyer/supplier.",
    mode: "info",
    screen: "profile",
    targetSelector: '[data-tour-id="profile-switch-company"]',
    accent: "success",
  },
  {
    id: "finish",
    eyebrow: "Готово",
    title: "Гайд завершен",
    description: "Повторно запустить его можно в экране «О приложении» через скрытый блок Advanced. Теперь маршрут пользователя стал заметно понятнее.",
    mode: "info",
    screen: "profile",
    accent: "success",
  },
];
